services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hones-dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=RemitDb
    ports:
      - '9500:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped
    ports:
      - '9520:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia
  
  email:
    image: rnwood/smtp4dev
    restart: unless-stopped
    ports:
      - "9510:80"
      - "2525:25"