services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hones-dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=RemitDb
    ports:
      - '9500:5432'
    
  rabbitmq:
    image: masstransit/rabbitmq:latest
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
        
  email:
    image: rnwood/smtp4dev
    restart: unless-stopped
    ports:
      - "9510:80"
      - "2525:25"